# Generated by Django 5.2.7 on 2025-11-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('release_year', models.PositiveIntegerField()),
                ('total_songs', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('real_name', models.CharField(max_length=100)),
                ('birth_year', models.PositiveIntegerField()),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('listeners', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producer',
            },
        ),
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'streaming_platform',
            },
        ),
        migrations.CreateModel(
            name='AlbumArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
            ],
            options={
                'db_table': 'album_artist',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(through='music_app.AlbumArtist', to='music_app.artist'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('release_year', models.PositiveIntegerField()),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_app.album')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_app.genre')),
                ('main_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='SongFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.song')),
            ],
            options={
                'db_table': 'song_feature',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='features',
            field=models.ManyToManyField(related_name='featured_songs', through='music_app.SongFeature', to='music_app.artist'),
        ),
        migrations.CreateModel(
            name='SongProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.producer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.song')),
            ],
            options={
                'db_table': 'song_producer',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='producers',
            field=models.ManyToManyField(through='music_app.SongProducer', to='music_app.producer'),
        ),
        migrations.CreateModel(
            name='SongAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.song')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.streamingplatform')),
            ],
            options={
                'db_table': 'song_availability',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='availability',
            field=models.ManyToManyField(through='music_app.SongAvailability', to='music_app.streamingplatform'),
        ),
    ]
