# Generated by Django 5.2.7 on 2025-12-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songfeature',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='songfeature',
            name='song',
        ),
        migrations.RemoveField(
            model_name='songproducer',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='songproducer',
            name='song',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='streamingplatform',
            name='platform_id',
        ),
        migrations.AddField(
            model_name='album',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='producer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='songavailability',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamingplatform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='music_app.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='origin_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='featured_songs', to='music_app.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='main_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_app.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='produced_songs', to='music_app.producer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='genre',
            table=None,
        ),
        migrations.AlterModelTable(
            name='producer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='song',
            table=None,
        ),
        migrations.AlterModelTable(
            name='songavailability',
            table=None,
        ),
        migrations.AlterModelTable(
            name='streamingplatform',
            table=None,
        ),
        migrations.CreateModel(
            name='SongDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('key_signature', models.CharField(blank=True, max_length=10, null=True)),
                ('structure', models.CharField(blank=True, max_length=50, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('instruments', models.CharField(blank=True, max_length=100, null=True)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='music_app.song')),
            ],
        ),
        migrations.DeleteModel(
            name='AlbumArtist',
        ),
        migrations.DeleteModel(
            name='SongFeature',
        ),
        migrations.DeleteModel(
            name='SongProducer',
        ),
    ]
