# Generated by Django 5.2.7 on 2025-12-11 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_remove_songfeature_artist_remove_songfeature_song_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.RemoveField(
            model_name='songavailability',
            name='link',
        ),
        migrations.RemoveField(
            model_name='streamingplatform',
            name='id',
        ),
        migrations.AddField(
            model_name='album',
            name='album_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='song',
            name='availability',
            field=models.ManyToManyField(through='music_app.SongAvailability', to='music_app.streamingplatform'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='streamingplatform',
            name='platform_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='origin_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='main_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='producer',
            table='producer',
        ),
        migrations.AlterModelTable(
            name='song',
            table='song',
        ),
        migrations.AlterModelTable(
            name='songavailability',
            table='song_availability',
        ),
        migrations.AlterModelTable(
            name='streamingplatform',
            table='streaming_platform',
        ),
        migrations.CreateModel(
            name='AlbumArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
            ],
            options={
                'db_table': 'album_artist',
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(through='music_app.AlbumArtist', to='music_app.artist'),
        ),
        migrations.CreateModel(
            name='SongFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.song')),
            ],
            options={
                'db_table': 'song_feature',
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='features',
            field=models.ManyToManyField(related_name='featured_songs', through='music_app.SongFeature', to='music_app.artist'),
        ),
        migrations.CreateModel(
            name='SongProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.producer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.song')),
            ],
            options={
                'db_table': 'song_producer',
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='producers',
            field=models.ManyToManyField(through='music_app.SongProducer', to='music_app.producer'),
        ),
        migrations.DeleteModel(
            name='SongDetail',
        ),
    ]
